name: iss
options:
  minimumXcodeGenVersion: 2.38.0
  deploymentTarget:
    macOS: "14.0"
  createIntermediateGroups: true
settings:
  SWIFT_VERSION: 5.9
  PRODUCT_BUNDLE_IDENTIFIER: com.instant-swipe.$(PRODUCT_NAME:rfc1034identifier)

targets:
  ISSApp:
    type: application
    platform: macOS
    sources:
      - path: Sources/ISSApp
      - path: Sources/Shared
    settings:
      base:
        PRODUCT_NAME: ISSApp
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_NSAppleEventsUsageDescription: Switch spaces instantly.
        INFOPLIST_KEY_NSHumanReadableCopyright: MIT
        SWIFT_OBJC_BRIDGING_HEADER: Sources/ISSApp/ISSApp-Bridging-Header.h
    dependencies:
      - target: ISSCLI

  ISSCLI:
    type: tool
    platform: macOS
    sources:
      - path: Sources/ISSCLI
      - path: Sources/Shared
    settings:
      base:
        PRODUCT_NAME: issctl
        GENERATE_INFOPLIST_FILE: YES
